#ifndef HARDWARE__MCP23017__VISIBILITY_CONTROL_H
#define HARDWARE__MCP23017__VISIBILITY_CONTROL_H

// This logic was borrowed (then namespaced) from the examples on the gcc wiki:
//     https://gcc.gnu.org/wiki/Visibility

#if defined _WIN32 || defined __CYGWIN__
#ifdef __GNUC__
#define MCP23017_HARDWARE_INTERFACE_EXPORT __attribute__((dllexport))
#define MCP23017_HARDWARE_INTERFACE_IMPORT __attribute__((dllimport))
#else
#define MCP23017_HARDWARE_INTERFACE_EXPORT __declspec(dllexport)
#define MCP23017_HARDWARE_INTERFACE_IMPORT __declspec(dllimport)
#endif
#ifdef MCP23017_HARDWARE_INTERFACE_BUILDING_DLL
#define MCP23017_HARDWARE_INTERFACE_PUBLIC MCP23017_HARDWARE_INTERFACE_EXPORT
#else
#define MCP23017_HARDWARE_INTERFACE_PUBLIC MCP23017_HARDWARE_INTERFACE_IMPORT
#endif
#define MCP23017_HARDWARE_INTERFACE_PUBLIC_TYPE MCP23017_HARDWARE_INTERFACE_PUBLIC
#define MCP23017_HARDWARE_INTERFACE_LOCAL
#else
#define MCP23017_HARDWARE_INTERFACE_EXPORT __attribute__((visibility("default")))
#define MCP23017_HARDWARE_INTERFACE_IMPORT
#if __GNUC__ >= 4
#define MCP23017_HARDWARE_INTERFACE_PUBLIC __attribute__((visibility("default")))
#define MCP23017_HARDWARE_INTERFACE_LOCAL __attribute__((visibility("hidden")))
#else
#define MCP23017_HARDWARE_INTERFACE_PUBLIC
#define MCP23017_HARDWARE_INTERFACE_LOCAL
#endif
#define MCP23017_HARDWARE_INTERFACE_PUBLIC_TYPE
#endif

#endif  // HARDWARE__MCP23017__VISIBILITY_CONTROL_H
