#ifndef HARDWARE__ADS7138__VISIBILITY_CONTROL_H
#define HARDWARE__ADS7138__VISIBILITY_CONTROL_H

// This logic was borrowed (then namespaced) from the examples on the gcc wiki:
//     https://gcc.gnu.org/wiki/Visibility

#if defined _WIN32 || defined __CYGWIN__
#ifdef __GNUC__
#define ADS7138_HARDWARE_INTERFACE_EXPORT __attribute__((dllexport))
#define ADS7138_HARDWARE_INTERFACE_IMPORT __attribute__((dllimport))
#else
#define ADS7138_HARDWARE_INTERFACE_EXPORT __declspec(dllexport)
#define ADS7138_HARDWARE_INTERFACE_IMPORT __declspec(dllimport)
#endif
#ifdef ADS7138_HARDWARE_INTERFACE_BUILDING_DLL
#define ADS7138_HARDWARE_INTERFACE_PUBLIC ADS7138_HARDWARE_INTERFACE_EXPORT
#else
#define ADS7138_HARDWARE_INTERFACE_PUBLIC ADS7138_HARDWARE_INTERFACE_IMPORT
#endif
#define ADS7138_HARDWARE_INTERFACE_PUBLIC_TYPE ADS7138_HARDWARE_INTERFACE_PUBLIC
#define ADS7138_HARDWARE_INTERFACE_LOCAL
#else
#define ADS7138_HARDWARE_INTERFACE_EXPORT __attribute__((visibility("default")))
#define ADS7138_HARDWARE_INTERFACE_IMPORT
#if __GNUC__ >= 4
#define ADS7138_HARDWARE_INTERFACE_PUBLIC __attribute__((visibility("default")))
#define ADS7138_HARDWARE_INTERFACE_LOCAL __attribute__((visibility("hidden")))
#else
#define ADS7138_HARDWARE_INTERFACE_PUBLIC
#define ADS7138_HARDWARE_INTERFACE_LOCAL
#endif
#define ADS7138_HARDWARE_INTERFACE_PUBLIC_TYPE
#endif

#endif  // HARDWARE__ADS7138__VISIBILITY_CONTROL_H